### ISSUE TITLE
Typo on json file

### ISSUE THREAD

**Issue by hormigaAzul** [platformio/platform-microchippic32#1]
There is a typo error on line 122 of the json file. Where it says **cchipKIT-application-32MX250F128.ld** it should say **chipKIT-application-32MX250F128.ld** This prevents compilation on the chipKit-pi board.

**Comment by hormigaAzul** [comment]
Sorry, wrong repo to report this

**Comment by hormigaAzul** [comment]
Although the same typo is preset on the chipkit_pi.json file

**Comment by ivankravets** [comment]
This is right repository. Thanks.

**Comment by ivankravets** [comment]
I'll fix it in PlatformIO 2.0 and 3.0
