### ISSUE TITLE
Chipkit_dp32 link error on EL Capitan

### ISSUE THREAD

**Issue by yamori813** [platformio/platform-microchippic32#11]
I use 3.5.4 on Mac OS X El capitan. I do build chipkit_dp32 target. I have error. I seem problem is fail in link script.

$ platformio run -vv
Processing chipkit_dp32 (platform: microchippic32; board: chipkit_dp32; framework: arduino)

PLATFORM: Microchip PIC32 > Digilent chipKIT DP32
SYSTEM: 32MX250F128B 40MHz 32KB RAM (120KB Flash)
pic32-g++ -o “/Users/hiroki/Develop/pio/pic32_test/src/main.ino.cpp” -x c++ -fpreprocessed -dD -E “/var/folders/8g/n2rkx2v94mnbtsxz0g8f70n00000gn/T/tmp_YOpSq”
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 28 compatible libraries
Scanning dependencies…
No dependencies
pic32-g++ -o .pioenvs/chipkit_dp32/src/main.ino.cpp.o -c -fno-exceptions -w -O2 -mdebugger -mno-smart-io -mprocessor=32MX250F128B -ffunction-sections -fdata-sections -Wcast-align -fno-short-double -ftoplevel-reorder -G1024 -DF_CPU=40000000L -DMPIDEVER=16777998 -DMPIDE=150 -DPLATFORMIO=30504 -D_BOARD_DP32_ -D_USE_USB_FOR_SERIAL_ -DARDUINO=10805 -DARDUINO_ARCH_PIC32 -DIDE=Arduino -Isrc -I/Users/hiroki/.platformio/packages/framework-arduinomicrochippic32/cores/pic32 -I/Users/hiroki/.platformio/packages/framework-arduinomicrochippic32/variants/DP32 src/main.ino.cpp
pic32-g++ -o .pioenvs/chipkit_dp32/firmware.elf -T chipKIT-application-32MX250F128.ld -w -Os -mdebugger -mprocessor=32MX250F128B -mno-peripheral-libs -nostartfiles -Wl,–gc-sections /Users/hiroki/.platformio/packages/framework-arduinomicrochippic32/cores/pic32/cpp-startup.S -Wl,–script=chipKIT-application-COMMON.ld .pioenvs/chipkit_dp32/src/main.ino.cpp.o -L.pioenvs/chipkit_dp32 -L/Users/hiroki/.platformio/packages/framework-arduinomicrochippic32/cores/pic32 -L/Users/hiroki/.platformio/packages/framework-arduinomicrochippic32/variants/DP32 -Wl,–start-group .pioenvs/chipkit_dp32/libFrameworkArduinoVariant.a .pioenvs/chipkit_dp32/libFrameworkArduino.a -lm -Wl,–end-group
/Users/hiroki/.platformio/packages/toolchain-microchippic32/bin/bin/gcc/pic32mx/4.8.3/…/…/…/…/bin/pic32-ld:chipKIT-application-COMMON.ld.00:55: warning: memory region kseg0_eeprom_mem' not declared /Users/hiroki/.platformio/packages/toolchain-microchippic32/bin/bin/gcc/pic32mx/4.8.3/../../../../bin/pic32-ld:chipKIT-application-COMMON.ld.00:61: warning: memory regionexception_mem’ not declared
/Users/hiroki/.platformio/packages/toolchain-microchippic32/bin/bin/gcc/pic32mx/4.8.3/…/…/…/…/bin/pic32-ld:chipKIT-application-COMMON.ld.00:456: warning: memory region kseg0_program_mem' not declared /Users/hiroki/.platformio/packages/toolchain-microchippic32/bin/bin/gcc/pic32mx/4.8.3/../../../../bin/pic32-ld:chipKIT-application-COMMON.ld.00:556: warning: memory regionconfigsfrs’ not declared
/Users/hiroki/.platformio/packages/toolchain-microchippic32/bin/bin/gcc/pic32mx/4.8.3/…/…/…/…/bin/pic32-ld:chipKIT-application-COMMON.ld.00:596: warning: memory region `kseg1_data_mem’ not declared
/Users/hiroki/.platformio/packages/toolchain-microchippic32/bin/bin/gcc/pic32mx/4.8.3/…/…/…/…/bin/pic32-ld: section .reset loaded at [9d001000,9d001007] overlaps section .startup loaded at [9d001000,9d0011ff]
collect2: error: ld returned 255 exit status
*** [.pioenvs/chipkit_dp32/firmware.elf] Error 255
========================== [ERROR] Took 1.57 seconds ==========================

**Comment by sstaub** [comment]
It seems I have the same problem with Fubarino Mini. Working on macOS Mojave Beta.
Compiling with Arduino IDE works.
<img width="1224" alt="microchip bug" src="https://user-images.githubusercontent.com/6450325/42895603-b5c5c94a-8aba-11e8-9ba9-c7a039c25d4c.png">

**Comment by sstaub** [comment]
adding 
platform = https://github.com/platformio/platform-microchippic32.git 
to platformio.ini solves the problem.
@ivankravets can you make a release?

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-microchippic32/releases/tag/v1.5.2

Thanks!

**Comment by yamori813** [comment]
Work fine. Thanks.
