### ISSUE TITLE
UDPEchoServer does not compile (with chipkit uC32)

### ISSUE THREAD

**Issue by ByranByran** [platformio/platform-microchippic32#4]
I'm currently trying to program my chipkit uC32 to deal with the Microchip ENC28J60-H (Olimex version of that chip) which is an Ethernet connector managed through the SPI connector of the chipkit.

I used the PmodNIC and DNETcK libraries given here :

https://github.com/DavidWrigley/RGB/tree/master/chipKIT/RGB_TEST/libary_backup1

When I compile the code given in the library (search UDPEchoServer) using MPIDE I can generate a UDP server. Anyway, it compiles and it works. I also tried on chipkit-core, I got an error concerning a too long definition. I corrected it by modifying the library and it works also with chipkit-core now (with some warnings about the casting but it works).

Anyway, I also tried to compile the included UDPEchoServer included in PlatformIO : .platformio/packages/framework-arduinomicrochippic32/libraries/DEIPcK/examples/UDPEchoServer/UDPEchoServer.ino and it doesn't work either. It seems that the error is the same : 

[error.txt](https://github.com/platformio/platform-microchippic32/files/463593/error.txt)

I checked in DEIPck.h and it seems that the classes are defined but are not recognized (I didn't find iPv4 BTW).

I also checked the DNETcK.h and it seems to contain iPv4 and the other classes but still not recognized.

**Comment by ByranByran** [comment]
I actually got this. I used to compile the .pde file in PlatformIO and the macro _cplusplus is not defined if the extension is not .cpp, after renamin my file main.cpp and some changes (links in DNETcK libraries), it finally worked. This is not a problem anymore.

**Comment by ivankravets** [comment]
Sure, you should use .CPP extension instead INO/PDE
