### ISSUE TITLE
New releases of chipKIT-core not being picked up

### ISSUE THREAD

**Issue by lstandage** [platformio/platform-microchippic32#8]
New versions of the chipKIT core are not being picked up when they are released. PlatformIO thinks the current version is 1.3.0, but there have been 1.3.1 and 1.4.0 releases in the meantime.

There is an upcoming 1.4.1 release planned, which is why this is coming up.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-microchippic32/releases/tag/v1.5.0
